### ISSUE TITLE
vagrant up failure

### ISSUE THREAD

**Issue by NicholasRees** [ska-telescope/ansible-playbooks#3] opened 2019-02-20 10:36 UTC
I am trying to accept SP-32 and got the following error:

```
TASK [ska-docker : Start the tango system] *************************************
task path: /vagrant/roles/ska-docker/tasks/main.yml:149
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<localhost> EXEC /bin/sh -c 'echo ~vagrant && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1550652532.49-67743927581245 `" && echo ansible-tmp-1550652532.49-67743927581245="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1550652532.49-67743927581245 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/commands/command.py
<localhost> PUT /home/vagrant/.ansible/tmp/ansible-local-3023hupVeP/tmp9KVko4 TO /home/vagrant/.ansible/tmp/ansible-tmp-1550652532.49-67743927581245/AnsiballZ_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1550652532.49-67743927581245/ /home/vagrant/.ansible/tmp/ansible-tmp-1550652532.49-67743927581245/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-vnfvstjhdskzcplahlmiqbkugfqmbszq; /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1550652532.49-67743927581245/AnsiballZ_command.py'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1550652532.49-67743927581245/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true, 
    "cmd": "cd /usr/src/ska-docker/docker-compose\n make up\n make start tangotest", 
    "delta": "0:00:33.717858", 
    "end": "2019-02-20 08:49:26.331769", 
    "invocation": {
        "module_args": {
            "_raw_params": "cd /usr/src/ska-docker/docker-compose\n make up\n make start tangotest", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 2, 
    "start": "2019-02-20 08:48:52.613911", 
    "stderr": "Creating volume \"docker-compose_tangodb\" with default driver\nPulling tangodb (ska-registry.av.it.pt/ska-docker/tango-db:latest)...\nGet https://ska-registry.av.it.pt/v2/ska-docker/tango-db/manifests/latest: Get https://ska-registry.av.it.pt:8080/auth?scope=repository%3Aska-docker%2Ftango-db%3Apull&service=Docker+registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\nmake: *** [minimal] Error 1\nPulling tangodb (ska-registry.av.it.pt/ska-docker/tango-db:latest)...\nGet https://ska-registry.av.it.pt/v2/ska-docker/tango-db/manifests/latest: Get https://ska-registry.av.it.pt:8080/auth?scope=repository%3Aska-docker%2Ftango-db%3Apull&service=Docker+registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\nmake: *** [minimal] Error 1", 
    "stderr_lines": [
        "Creating volume \"docker-compose_tangodb\" with default driver", 
        "Pulling tangodb (ska-registry.av.it.pt/ska-docker/tango-db:latest)...", 
        "Get https://ska-registry.av.it.pt/v2/ska-docker/tango-db/manifests/latest: Get https://ska-registry.av.it.pt:8080/auth?scope=repository%3Aska-docker%2Ftango-db%3Apull&service=Docker+registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", 
        "make: *** [minimal] Error 1", 
        "Pulling tangodb (ska-registry.av.it.pt/ska-docker/tango-db:latest)...", 
        "Get https://ska-registry.av.it.pt/v2/ska-docker/tango-db/manifests/latest: Get https://ska-registry.av.it.pt:8080/auth?scope=repository%3Aska-docker%2Ftango-db%3Apull&service=Docker+registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", 
        "make: *** [minimal] Error 1"
    ], 
    "stdout": "DISPLAY=:0.0 XAUTHORITY=/hosthome/.Xauthority TANGO_HOST=ubuntu-bionic:10000 NETWORK_MODE=host XAUTHORITY_MOUNT=/tmp/.X11-unix:/tmp/.X11-unix MYSQL_HOST=ubuntu-bionic:3306 CONTAINER_NAME_PREFIX= COMPOSE_IGNORE_ORPHANS=true docker-compose -f tango.yml up -d\nMakefile:102: recipe for target 'minimal' failed\nDISPLAY=:0.0 XAUTHORITY=/hosthome/.Xauthority TANGO_HOST=ubuntu-bionic:10000 NETWORK_MODE=host XAUTHORITY_MOUNT=/tmp/.X11-unix:/tmp/.X11-unix MYSQL_HOST=ubuntu-bionic:3306 CONTAINER_NAME_PREFIX= COMPOSE_IGNORE_ORPHANS=true docker-compose -f tango.yml up -d\nMakefile:102: recipe for target 'minimal' failed", 
    "stdout_lines": [
        "DISPLAY=:0.0 XAUTHORITY=/hosthome/.Xauthority TANGO_HOST=ubuntu-bionic:10000 NETWORK_MODE=host XAUTHORITY_MOUNT=/tmp/.X11-unix:/tmp/.X11-unix MYSQL_HOST=ubuntu-bionic:3306 CONTAINER_NAME_PREFIX= COMPOSE_IGNORE_ORPHANS=true docker-compose -f tango.yml up -d", 
        "Makefile:102: recipe for target 'minimal' failed", 
        "DISPLAY=:0.0 XAUTHORITY=/hosthome/.Xauthority TANGO_HOST=ubuntu-bionic:10000 NETWORK_MODE=host XAUTHORITY_MOUNT=/tmp/.X11-unix:/tmp/.X11-unix MYSQL_HOST=ubuntu-bionic:3306 CONTAINER_NAME_PREFIX= COMPOSE_IGNORE_ORPHANS=true docker-compose -f tango.yml up -d", 
        "Makefile:102: recipe for target 'minimal' failed"
    ]
}
	to retry, use: --limit @/vagrant/deploy_tangoenv.retry

PLAY RECAP *********************************************************************
localhost                  : ok=39   changed=34   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
nrees-lt:ansible-playbooks n.rees$ 
nrees-lt:ansible-playbooks n.rees$ uname -a
Darwin nrees-lt.cpt.kat.ac.za 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

```
Let me know what to do.

**Comment by Matteo04052017** [comment] 2019-02-20 15:40
There is a timeout error in the last job of the playbook. I have seen it once on my laptop but I couldn't reproduce it. Can I ask you to do a couple of tests for me? 

The first one is to open the virtual box created and start the tango system manually? To do it just call (from bash) the following commands:
1) cd /usr/src/ska-docker/docker-compose
2) make up
3) make start tangotest
4) jive

The second one (to be done after the first one) is to restart the playbook from vagrant. You can do that calling "vagrant up && vagrant provision".

Let me know.

**Comment by NicholasRees** [comment] 2019-02-21 07:24
Sorry for the delay, I haven't turned on notifications... I assume you mean to run the first series of commands on the VM. Just tried it and got:

```
nrees-lt:ansible-playbooks n.rees$ vagrant ssh

Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu Feb 21 07:22:00 UTC 2019

  System load:  0.0               Processes:              113
  Usage of /:   69.2% of 9.63GB   Users logged in:        0
  Memory usage: 9%                IP address for enp0s3:  10.0.2.15
  Swap usage:   0%                IP address for docker0: 172.17.0.1


  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

9 packages can be updated.
7 updates are security updates.


*** System restart required ***
Last login: Thu Feb 21 07:20:41 2019 from 10.0.2.2

vagrant@ubuntu-bionic:~$ 
vagrant@ubuntu-bionic:~$ cd /usr/src/ska-docker/docker-compose
vagrant@ubuntu-bionic:/usr/src/ska-docker/docker-compose$ make up
DISPLAY=:0.0 XAUTHORITY=/hosthome/.Xauthority TANGO_HOST=ubuntu-bionic:10000 NETWORK_MODE=host XAUTHORITY_MOUNT=/tmp/.X11-unix:/tmp/.X11-unix MYSQL_HOST=ubuntu-bionic:3306 CONTAINER_NAME_PREFIX= COMPOSE_IGNORE_ORPHANS=true docker-compose -f tango.yml up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Makefile:102: recipe for target 'minimal' failed
make: *** [minimal] Error 1
vagrant@ubuntu-bionic:/usr/src/ska-docker/docker-compose$ 
```

**Comment by NicholasRees** [comment] 2019-02-21 07:31
Also, dockerd seems to be running:
```
vagrant@ubuntu-bionic:~$ cd /usr/src/ska-docker/docker-compose
vagrant@ubuntu-bionic:/usr/src/ska-docker/docker-compose$ make up
DISPLAY=:0.0 XAUTHORITY=/hosthome/.Xauthority TANGO_HOST=ubuntu-bionic:10000 NETWORK_MODE=host XAUTHORITY_MOUNT=/tmp/.X11-unix:/tmp/.X11-unix MYSQL_HOST=ubuntu-bionic:3306 CONTAINER_NAME_PREFIX= COMPOSE_IGNORE_ORPHANS=true docker-compose -f tango.yml up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Makefile:102: recipe for target 'minimal' failed
make: *** [minimal] Error 1
vagrant@ubuntu-bionic:/usr/src/ska-docker/docker-compose$ ps -ef | grep dock
root     13695     1  0 Feb20 ?        00:00:07 /usr/bin/dockerd -H fd://
```

**Comment by NicholasRees** [comment] 2019-02-21 08:09
Rebooted at Matteo's request:
```
vagrant@ubuntu-bionic:/usr/src/ska-docker/docker-compose$ sudo reboot
Connection to 127.0.0.1 closed by remote host.
Connection to 127.0.0.1 closed.
nrees-lt:ansible-playbooks n.rees$ vagrant ssh
Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu Feb 21 08:07:52 UTC 2019

  System load:  0.08              Processes:              152
  Usage of /:   69.2% of 9.63GB   Users logged in:        0
  Memory usage: 11%               IP address for enp0s3:  10.0.2.15
  Swap usage:   0%                IP address for docker0: 172.17.0.1


  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

9 packages can be updated.
7 updates are security updates.


Last login: Thu Feb 21 07:27:44 2019 from 10.0.2.2
vagrant@ubuntu-bionic:~$ cd /usr/src/ska-docker/docker-compose
vagrant@ubuntu-bionic:/usr/src/ska-docker/docker-compose$ make up
DISPLAY=:0.0 XAUTHORITY=/hosthome/.Xauthority TANGO_HOST=ubuntu-bionic:10000 NETWORK_MODE=host XAUTHORITY_MOUNT=/tmp/.X11-unix:/tmp/.X11-unix MYSQL_HOST=ubuntu-bionic:3306 CONTAINER_NAME_PREFIX= COMPOSE_IGNORE_ORPHANS=true docker-compose -f tango.yml up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Makefile:102: recipe for target 'minimal' failed
make: *** [minimal] Error 1
vagrant@ubuntu-bionic:/usr/src/ska-docker/docker-compose$ ps -ef | grep dock
root      1303     1  0 08:07 ?        00:00:00 /usr/bin/dockerd -H fd://
vagrant   2200  2176  0 08:08 pts/0    00:00:00 grep --color=auto dock
vagrant@ubuntu-bionic:/usr/src/ska-docker/docker-compose$ 
```

**Comment by Matteo04052017** [comment] 2019-02-21 09:23
Thanks Nick, you found two errors! The first one is a bug (the fact that you have to call docker with sudo) and the second one is the network issue (perhaps a firewall from where you are). 

I am working on the first one, for the second we have to do more tests. I will update you asap.

**Comment by NicholasRees** [comment] 2019-02-21 09:25
The full log of the original build is:

[log.txt](https://github.com/ska-telescope/ansible-playbooks/files/2888537/log.txt)

**Comment by Matteo04052017** [comment] 2019-02-21 11:14
OK, we found a solution for both errors. 
The network error has been solved changing the port of the registry (from 8080 to 80). 
I have made a fix into the ska-docker role so that the user 'vagrant' can access directly to docker. 

Can you try to provision (command "vagrant provision" if running) the box again after pulling the latest changes from git? 

If you don't want to re-install what has already been installed, you can modify the file "deploy_tangoenv.yml" changing some variables like this:
    build_tango: 'no'
    install_mysql: 'no'
    start_mysql_server: 'no'
    install_pytango: 'no'
    install_ide: 'no'
    install_ska_docker: 'yes'
    start_tango: 'yes'
    update_hosts: 'yes'

Let me know if there are any other problem. 

Thanks.

**Comment by NicholasRees** [comment] 2019-02-21 11:45
<<<
nrees-lt:ansible-playbooks n.rees$ vagrant provision
==> default: Running provisioner: ansible_local...
`playbook` does not exist on the guest: /vagrant/deploy_tangoenv.yml
>>>

**Comment by Matteo04052017** [comment] 2019-02-21 14:04
Yes, perhaps you only need to restart the box with "vagrant halt && vagrant up --provision".

It should work...

**Comment by Matteo04052017** [comment] 2019-04-02 10:00
Removed vagrant from the developer portal. As soon as Marco will approve it, I will close this issue.

**Closed** 2019-04-02 10:13 UTC
